# Generated by Django 4.1.3 on 2022-11-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
